version: '3'

services:
  dataapi:
    build: data_api/
    env_file:
      - ./data_api/.env
      #- /home/cloud-service/data_api/.env
      #- /home/whale/cloud_service/data_api/.env
    command: python web_app.py
    expose:
      - '5000'
    ports:
      - 5000:5000
    networks:
      - weathernet
    depends_on:
      - localrabbit
  weatherapi:
    build: weather_api/
    restart: unless-stopped
    env_file:
      - ./weather_api/config/.env
      #- /home/cloud-service/weather_api/config/.env
      #- /home/whale/cloud_service/weather_api/config/.env
    command: python -u weather_api.py
    networks:
      - weathernet
    depends_on:
      - localrabbit
      - localredis
  viewapi:
    build:
      context: ./view_api
      dockerfile: Dockerfile
      args:
        DOMAIN_NAME: ${DOMAIN_NAME}
    env_file:
      - ./view_api/.env
      #- /home/cloud-service/view_api/.env
      #- /home/whale/cloud_service/view_api/.env
    command: /usr/bin/supervisord
    networks:
      - weathernet
    ports:
      - 8080:80
    depends_on:
      - localrabbit
      - localdb
  localrabbit:
    image: rabbitmq:management
    hostname: rabbithost
    networks:
      - weathernet
    ports:
      - 15672:15672
  localdb:
    image: mysql
    hostname: dbhost
    networks:
      - weathernet
    environment:
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
  localredis:
    image: redis
    hostname: localredis
    networks:
      - weathernet

networks:
  weathernet:
    driver: bridge